<%@ Page Title="Giới Thiệu" Language="VB" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="About.aspx.vb" Inherits="Nhom1_DTDM.About" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <hgroup class="title">
        <h1>Giới Thiệu</h1>
    </hgroup>

    <article>
       <p>        
            &nbsp;</p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span style="font-size: 14px; line-height: 16.1px; font-family: Arial, serif;">Chế độ chính sách cho người lao động và quan tâm đến đời sống của<span class="Apple-converted-space">&nbsp;</span>cán bộ nhân viên<span class="Apple-converted-space">&nbsp;</span>với phương châm cho<span class="Apple-converted-space">&nbsp;</span>cán bộ nhân viên<span class="Apple-converted-space">&nbsp;</span>có một cuộc sống “đầy đủ về vật chất và phong phú về tinh thần”. Chính sách này được xây dựng căn cứ trên các tiêu chí: tương xứng với kết quả công việc, đóng góp cho FPT; cạnh tranh theo thị trường; khuyến khích tăng kết quả và chất lượng công việc; công bằng và minh bạch.</span></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <b><span style="font-size: 14px; line-height: 16.1px; font-family: Arial, serif;">Môi trường là việc:</span></b></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span style="font-size: 14px; line-height: 16.1px; font-family: Arial, serif;">FPT Shop<span class="Apple-converted-space">&nbsp;</span>là chiếc cầu nối gắn kết<span class="Apple-converted-space">&nbsp;</span>những thành viên<span class="Apple-converted-space">&nbsp;</span>với nhau , giúp<span class="Apple-converted-space">&nbsp;</span>mọi người<span class="Apple-converted-space">&nbsp;</span>làm việc hăng say cho sự nghiệp phát triển của công ty<span class="Apple-converted-space">&nbsp;</span>và thăng tiến cho bản thân.</span></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span style="font-size: 14px; line-height: 16.1px; font-family: Arial, serif;">Đến với FPT Shop để cùng làm việc, phát triển trong một môi trường trẻ trung, năng động, thân thiện . Tạo một sân chơi công bằng và cạnh tranh lành mạnh cho toàn thể cán bộ nhân viên công ty có cơ hội thể hiện và phát huy tối đa tiềm lực của mình.</span></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <b><span style="font-size: 14px; line-height: 16.1px; font-family: Arial, serif;">Đào tạo chuyên nghiệp và hoàn toàn miễn phí</span></b></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span style="font-size: 14px; font-family: Arial, serif;">FPT<span class="Apple-converted-space">&nbsp;</span>Shop<span class="Apple-converted-space">&nbsp;</span>khuyến khích và tạo điều kiện tốt nhất cho mọi<span class="Apple-converted-space">&nbsp;</span>cán bộ nhân viên<span class="Apple-converted-space">&nbsp;</span>phát triển toàn diện về cả năng lực chuyên môn và kỹ năng mềm không chỉ thông qua công việc, mà còn qua đào tạo, tự đào tạo và trao đổi kiến thức. điều này được thể hiện qua việc,<span class="Apple-converted-space">&nbsp;</span>liên tục tổ chức các chương trình đào tạo thuê ngoài và tự đào tạo.</span></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span style="font-size: 14px; font-family: Arial, serif;">Bằng sự thấu hiểu và tận tâm của đội ngủ quản lý, các cán bộ đào tạo, chúng tôi thiết kế các chương trình đào tạo với lượng kiến thức phù hợp với từng vị trí công việc. Với các phương pháp truyền tải đa dạng, sinh động kết hợp lý thuyết và thực hành nhằm nâng cao kỹ năng cho nhân viên. Tất cả những kiến thức, kỹ năng đó sẽ giúp các bạn hoàn thành tốt công việc và là hành trang theo bạn trong suốt quá trình phát triển sự nghiệp. Và dĩ nhiên các khóa đào tạo này là hoàn toàn miễn phí vì chúng tôi tâm niệm rằng “ Công ty đào tạo cho nhân viên của mình để cùng thành công và phát triển với công ty”</span></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span style="font-size: 14px; font-family: Arial, serif;">Về đối tượng được tham dự đào tạo có cả nhân viên mới vào công ty và bồi dưỡng cho nhân viên đang làm việc.</span></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <b><span style="font-size: 14px; font-family: Arial, serif;">Thu nhập hấp dẫn, phù hợp với năng lực bản thân.</span></b></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span style="font-size: 14px; font-family: Arial, serif;">Tùy từng vị trí làm việc tại công ty mà chúng tôi có cơ cấu thu nhập riêng dựa trên cơ cấu Lương căn bản và thưởng theo năng lực. Trên cơ sở cùng chia sẻ thành công, thu nhập của các bạn nhận được sẽ xứng đáng với những gì bạn đóng góp vào sự phát triển và thành công của công ty</span></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <b><span style="font-size: 14px; font-family: Arial, serif;">Tham gia đầy đủ các chế độ bảo hiểm.</span></b></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span style="font-size: 14px; font-family: Arial, serif;">Các chế độ bảo hiểm y tế, bảo hiểm xã hội và bảo hiểm thất nghiệp sẽ được công ty tham gia đầy đủ theo đúng qui định của luật lao động.</span></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            &nbsp;</p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            &nbsp;</p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <b><span style="font-size: 14px; font-family: Arial, serif;">Cơ hội thăng tiến rõ ràng, lộ trình phát triển cụ thể.</span></b></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span style="font-size: 14px; font-family: Arial, serif;">Với sự phát triển liên tục và mở rộng chuổi cửa hàng trên toàn quốc, chúng tôi mang đến cho nhân viên công ty, những người có sự nổ lực trong công việc và gắn bó với công ty từ 6 tháng trở lên cơ hội được phát triển nghề nghiệp của mình với những vị trí cao hơn.</span></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span style="font-size: 14px; font-family: Arial, serif;">Đối với các vị trí khối cửa hàng, công ty sẽ đánh giá nhân viên theo từng đợt dựa trên những tiêu chí cụ thể cho từng vị trí để chọn lựa những ứng cử viên xuất sắc tham dự phỏng vấn và đào tạo cho vị trí cao hơn.</span></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span style="font-size: 14px; font-family: Arial, serif;">Đối với các vị trí khối văn phòng, chúng tôi luôn đưa ra lộ trình phát triển cụ thể theo từng giai đoạn đối với mỗi cá nhân.</span></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <span style="font-size: 14px; font-family: Arial, serif;">Việc thuyên chuyển các vị trí và bộ phận trong công ty của nhân viên đã làm đủ sáu tháng trỡ lên cũng sẽ được ưu tiên trước. Bên cạnh đó việc thuyên chuyển sang những công ty thành viên trực thuộc tập đoàn cũng sẽ dễ dàng hơn.</span></p>
        <p style="color: rgb(68, 68, 68); font-family: Arial, Verdana, sans-serif; font-size: 14px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 22px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
            <b><i><span style="font-size: 14px; font-family: Arial, serif;">Ngoài ra công ty cũng kết hợp với tập đoàn thường xuyên tổ chức các hoạt động hội thao, hội diễn, văn nghệ, tân niên, tất niên, họp mặt… hằng năm cho nhân viên.</span></i></b></p>
    </article>

    <aside>
        <ul>
            <li><a runat="server" href="~/">Trang Chủ</a></li>
            <li><a runat="server" href="~/About.aspx">Giới Thiệu</a></li>
            <li><a runat="server" href="~/Contact.aspx">Liên Hệ</a></li>
        </ul>
    </aside>
</asp:Content>